/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author matias
 */
public class pantallaCarga extends javax.swing.JFrame {
public int animacionDuracionEnMilisegundos = 12000; // Duración de la animación en milisegundos
 private boolean animacionCompletada = false; // Declaración de la variable
    /**
     * Creates new form pantallaCarga
     */
    public pantallaCarga() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pantallaCargaLista.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLabel1ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel1ComponentResized
     
        
        if (!animacionCompletada) {
        Timer timer = new Timer(animacionDuracionEnMilisegundos, e -> {
            // Esta parte se ejecutará cuando termine la animación

            // Puedes crear y mostrar la nueva ventana aquí
            vistaPrncipal nuevaVentana = new vistaPrncipal();
            nuevaVentana.setVisible(true);

            // Cierra la ventana actual si es necesario
            dispose(); // Esto cerrará la ventana actual
        });
        timer.setRepeats(false); // Hacer que el temporizador se ejecute solo una vez
        timer.start();
        
        animacionCompletada = true; // Marcar que la animación ha sido completada
    }
    // Obtén el tamaño actual del JLabel 
    int width = jLabel1.getWidth();
    int height = jLabel1.getHeight();

    // Obtén el icono actual del JLabel
    ImageIcon iconoactual = (ImageIcon) jLabel1.getIcon();

    // Obtén la imagen actual del icono
    Image imagenactual = iconoactual.getImage();

    // Redimensiona la imagen del icono para que coincida con el tamaño actual
    Image escaladodeimagen = imagenactual.getScaledInstance(width, height, Image.SCALE_DEFAULT);

    // Crea un nuevo ImageIcon redimensionado y configúralo en el JLabel
    ImageIcon redimensionado = new ImageIcon(escaladodeimagen);

    // Establece el nuevo ImageIcon en el JLabel
    jLabel1.setIcon(redimensionado);
    }//GEN-LAST:event_jLabel1ComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallaCarga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
